version: '3.8'

services:
    app:
        image: streamlit-docker
        build:
            dockerfile: ./Dockerfile
            context: .
        environment:
            - PORT=${PORT}
        ports:
            - "8000:8501"
        